### ISSUE TITLE
Versioning charts

### ISSUE THREAD

**Issue by technosophos** [helm/helm-classic#199]
From the very beginning each chart declares a version number in its `Chart.yaml`. But we need a way to reference previous versions of a chart, and preferably do so without having to alter the underlying Git repo (e.g. checking out an earlier release).

Some methods observed in the wild or suggested to us:

- Homebrew "version repo": The main repo only has latest. A separate `homebrew-versions` repo has versioned artifacts: https://github.com/Homebrew/homebrew-versions
- Filename: The chart filename contains an explicit version (`foo-1.2.3`), and all versions are kept in the repo.
    - Apt: Provide only specific versions of a package, but provide possibly more than one. (foo-1.2.3, foo-1.4.5, foo->foo-1.4.5)
    - versions are conventional by suffix (?)
- Berkshelf-style: Every project gets its own versioned repo, not really a viable option for our model
- Subdirectories model:
   - Each chart has version subdirectories (`alpine/0.0.1/Chartfile.yaml`)
   - Symlinks provide `latest`, `beta`, etc
- Pure Git (aka "the Godeps model"): "version" is just a SHA
- External: "version" is tied explicitly to the remote image repo (e.g. the version on GCR, Quay, or DockerHub). Downside: no way of versioning changes to the manifests (and if we add one, we re-introduce the problem this ostensibly solves).

I'd really like to get this right, and do it well in advance of 1.0. Suggestions? Pros/cons to any of these methods?

**Comment by mattfarina** [comment]
This is a hard problem when doing things in a homebrew style. Some questions and thoughts come to mind:

* Is there a way to automate the `-versions` repo? `homebrew-versions` is pretty sparse because people need to choose to put things in there?
* If you are explicit about the versions (`foo-1.2.3`) it means the checkout will steadily grow in size which may be a pain. The same with doing things by directory for the version.
* In homebrew the pull requests for updates are in the style `glide 0.7.0`. You have the name, a space, and the version. This pattern could be enforced with a bot. Could a command search the git repo for the old version from the commit message, check it out, do something with it, and then checkout the master? Feels weird and I'm not sure how that scales.
* The final bullet, with the version only being for the remote image, get's weird if config doesn't always match the image. Wouldn't that become an issue easily?
* I like the benefits of the Berkshelf-style.

This is my first pass reaction. After pondering this a little more I may have more to share.

**Comment by technosophos** [comment]
Here's a way of using Git tags to essentially give us a versioned record of every chart in a way where we can easily extract any versioned chart (without having to do any Git special checkouts): https://gist.github.com/technosophos/c1dc0924afd234d35e9e

**Comment by pat2man** [comment]
CocoaPods uses the subdirectory model without any sort of latest beta symlink. That information could just come out of the Chartfile.

Example: https://github.com/CocoaPods/Specs/tree/master/Specs/NewRelicAgent

**Comment by krancour** [comment]
@technosophos, I read over your proposal (from way back in November) and in general, I like the idea, but I'm wondering if, with multiples charts per repository, it would get pretty confusing pretty quickly.  I think it would, because if we tag repos with a tag for a _chart_ within that's been revved, there's no way to understand quickly and easily what version all the _other_ charts in that same repo are at in that particular ref.

**Comment by mboersma** [comment]
The future of Helm is at [kubernetes/helm](https://github.com/kube:brnetes/helm). Helm Classic is in maintenance mode, so I'm closing this proposal. ☑️
