### ISSUE TITLE
Allow for specifying type when installing a chart

### ISSUE THREAD

**Issue by rafaljanicki** [helm/helm-classic#379]
Hello,

On AWS infrastructure you need to specify a type argument to LoadBalancer when exposing a rc in order to acquire public IP (DNS to be exact). Therefore, installing on AWS using Helm right now is not going to work.

**Comment by krancour** [comment]
Helm allows you to customize charts before installation.  Instead of `helm install <chart>`, follow these steps instead:

1.  Fetch the chart from the local cache into the helm "workspace":

```
$ helm fetch <chart>
```

2.  Edit the chart:

```
$ EDITOR=vi helm edit <chart>
```

3.  Install as usual:

```
$ helm install <chart>
```

With all this being said, I know that the `deis` and `deis-dev` charts from https://github.com/deis/charts currently account for most helm usage.  If that's the chart you're asking about, specifically, then be advised that the `deis-router-service` already has type set to `LoadBalancer`.  This works great on AWS and GKE and causes no harm on other platforms.  The `deis-router` is the single point of ingress for traffic to the other Deis components and to applications deployed via Deis.  There should be no need to add `TypeL LoadBalancer` to any other service.  If this sounds applicable to you, there are more docs available on this topic under https://github.com/deis/router.

Back to the general case, #339 has added support for templated/parameterized charts that will allow chart authors to better plan for considerations such as the one you've raised.

Does this help?

**Comment by rafaljanicki** [comment]
Thanks for swift response.

Actually deis is not my case here, I've started to use Kubernetes on AWS (using official docs) and then wanted to deploy Jenkins with helm. Everything worked like a charm except being deployed w/o public DNS as Kubernetes on AWS requires type=LoadBalancer to be public.

So, let's say, I'm a cloud agnostic company and I deploy applications on many clouds to have safer redundancy. In order to do that, I need to automate it a bit, so I don't deploy apps to clouds by hand. I find editing chart harder to automate, because it's an operation on a file and therefore it's more error-prone (e.g. a small change may cause incorrect chart).
On the other hand, adding a flag to define which is supported already by Kubernetes would allow me to easily deploy apps by only using "personalized" commands.

The parameterization of charts might help here, but it requires every dev to remember about that which often results in not remembering about that ;)

Best,
Rafal

**Comment by bacongobbler** [comment]
also related to this discussion: https://github.com/helm/helm/issues/108#issuecomment-152037515

> The parameterization of charts might help here, but it requires every dev to remember about that which often results in not remembering about that ;)

If you're concerned about forgetting the parameterization of the charts, the simplest solution to this would be to first generate the chart using that tool and then [create and maintain your own chart repository](https://github.com/helm/helm/blob/master/docs/workspace.md#scenario-1-the-workspace-team-repo). Once that's created, users of your company can then just fetch your chart from your repo and install it. If they need to change the type from LoadBalancer to something else, then they can edit the chart, make their changes and push it up to their own repository. Either that or run it through their own generator.

At this point we're just trying to gather feedback, and as @krancour mentioned there is a generator tool that should help with this use case. Does the above workflow work for you?

**Comment by mboersma** [comment]
There are some good workarounds proposed here, and this hasn't been touched since January. I'm closing this, but please re-open it if you have a backward-compatible `helmc` solution in mind. Helm Classic is in maintenance mode.

Please see [kubernetes/helm](https://github.com/kubernetes/helm) for the future of Helm development.
