### ISSUE TITLE
Plan for helm/helm?

### ISSUE THREAD

**Issue by mattfarina** [helm/helm-classic#427]
I've been looking at [kubernetes/helm](https://github.com/kubernetes/helm) and I see it's both a major change and not usable as a replacement for helm/helm at this time. What's the plan for helm/helm until kubernetes/helm is viable to use instead?

I would personally like to see it stay around and be maintained until kubernetes/helm has been released for at least 6 months.

**Comment by seeekr** [comment]
FWIW, my perspective as someone who just learned about the (very cool!) Helm project: I'm confused about how helm/helm and k8s/helm differ and what the plan is going forward. It seems that there are some really nice things in k8s/helm that are (afaict) not in helm/helm... -- and I wanted to say, "and helm/helm still being actively developed". But then I checked contribution graphs for both projects and now it's clear that k8s/helm is going to be "the" helm going forward.
Should ideally be stated in this project's readme and on the deis blog on the entries that talk about helm. Would lessen the confusion for newbies such as myself :) Cheers.

**Comment by krancour** [comment]
Looks like @sgoings has already opened an issue to address this in the documentation.  In the meantime, I can shed a little bit of light on it for those who have inquired here...

k8s/helm is the next generation helm.  helm/helm is strictly a client-based tool.  Apart from the k8s apiserver itself, there is no server side component to it.  i.e. No state re: installed charts or configuration thereof is held anywhere on the server side.  This doesn't work out so hot for anyone wishing to gracefully handle ongoing cluster maintenance from multiple laptops or to share that responsibility with teammates.

k8s/helm is integrated with a new/improved k8s deployment manager so that all the state moves to the server side.

All that being said, k8s/helm isn't ready for prime time and classic helm is the only way to facilitate installation of Deis Workflow... so if you see _any_ active development in helm/helm, it is in part because the Deis team very much depends on it.  k8s/helm, however, is the strategic direction (and has been accepted into CNCF with the rest of k8s).

**Comment by krancour** [comment]
Since the question has been answered and the efforts applied toward the Helm Classic 0.7.0 release should clear up any remaining confusion (see #450) I'm going to close this.
